### ISSUE TITLE
for @Ana https://github.com/datascience-mobi-2023/topic05_team03/blob/main/Project%20Code%20Phase%20II.Rmd#L740

### ISSUE THREAD

**Issue by aluisascosta** [datascience-mobi-2023/topic05_team03#4]

**Comment by RobertSchwarz1** [comment]
@aluisascosta Hi Ana! Thank you for taking a look! I have made some clarifications starting with line 991 of my "Project Code Phase II" file. Can you run everything now? If not, please let me know:)
Thank you very much!
