### ISSUE TITLE
@Ana Hi, thanks for taking a look! I was talking about the code starting from line 601 where I tried to order the columns. The rows did indeed work fine.

### ISSUE THREAD

**Issue by aluisascosta** [datascience-mobi-2023/topic05_team03#5]

**Comment by aluisascosta** [comment]
@Robert actually the issue is that order_actual_cnv_columns and order_target_cnv_columns do not have the same dimension. You need to:

`new_prism.cnv = copy_prism.cnv[,intersect(order_actual_cnv_columns, order_target_cnv_columns)]`

**Comment by RobertSchwarz1** [comment]
Hey Ana, thank you! I have added this. My intent is to make the columns adopt the order of prism.achilles (alphabetical order), just like I did so often with the cell lines. Still, this doesn't seem to work. Could you please take another look at it? Thank you

**Comment by aluisascosta** [comment]
Hi Robert, in that case you will need to first take the intersect of the column names and next order the resulting character vector alphabetically. You can use the sort() function for this.

**Comment by RobertSchwarz1** [comment]
Alright! Thank you!
