### ISSUE TITLE
Verify correlation calculation

### ISSUE THREAD

**Issue by aluisascosta** [datascience-mobi-2023/topic05_team03#7]
https://github.com/datascience-mobi-2023/topic05_team03/blob/0c421cff35df7bb9418d791b851e2fd71fb32c64/correlation_drug_geneknockout.Rmd#L180

**Comment by aluisascosta** [comment]
@artankry Can you tell me more about the issue here? I am struggling to understand the aim of the code chunk and I also cannot reproduce it because I am missing the value `highly_correlated_drugs`.

**Comment by aluisascosta** [comment]
Hi @artankry, 

On point 2 and 3 I would suggest that if you have a small amount of NAs (e.g more than 2) you can replace them with the mean maybe. But if all are NAs, you can simply remove it. 

You have a chunk that it took me forever to run and I am guessing you are running the correlation on more than you think you are. If this alright with you, you can keep doing it, but just in case, check if you are selecting **just** gene X and gene X in the 2 different data frames, as in the end, you should get just one single value of correlation per gene.

Finally, maybe the low correlation values are normal. As long as it seems to be more or less consistent between all genes, this should be alright. How are you handling treatment which have more than one target?

**Comment by artankry** [comment]
Hey Ana, I am sorry for not replying. I did not see the email. I do not include the drugs with multiple targets in the analysis, as a we have no data on how multiple gen knockouts at the same time do affect the cell.
